language: go
sudo: false
go:
  - "1.15.x"
env:
  global:
    - GO111MODULE=on
script:
  - go test -v -cover ./...
  - go vet ./...
  - go run golang.org/x/lint/golint -set_exit_status ./...
  - go run github.com/fzipp/gocyclo/cmd/gocyclo -avg .
notifications:
  email:
    on_success: change
    on_failure: change
