// Code generated by prana; DO NOT EDIT.

// Package model contains an object model of database schema 'public'
// Auto-generated at Mon, 04 Sep 2023 21:52:17 UTC

package model

import "time"

// Lock represents a data base table 'locks'
type Lock struct {
	// Name represents a database column 'name' of type 'CHARACTER VARYING(255) PRIMARY KEY NOT NULL'
	Name string `db:"name,primary_key,not_null,size=255"`
	// RecordVersionNumber represents a database column 'record_version_number' of type 'BIGINT(64) NULL'
	RecordVersionNumber *int64 `db:"record_version_number,null"`
	// Data represents a database column 'data' of type 'BYTEA NULL'
	Data []byte `db:"data,null"`
	// Owner represents a database column 'owner' of type 'CHARACTER VARYING(255) NULL'
	Owner *string `db:"owner,null,size=255"`
}

// Message represents a data base table 'messages'
type Message struct {
	// ID represents a database column 'id' of type 'INTEGER(32) PRIMARY KEY NOT NULL'
	ID int `db:"id,primary_key,not_null"`
	// Message represents a database column 'message' of type 'JSONB NOT NULL'
	Message []byte `db:"message,not_null"`
	// Published represents a database column 'published' of type 'BOOLEAN NOT NULL'
	Published bool `db:"published,not_null"`
	// CreatedAt represents a database column 'created_at' of type 'TIMESTAMP WITH TIME ZONE NOT NULL'
	CreatedAt time.Time `db:"created_at,not_null"`
	// UpdatedAt represents a database column 'updated_at' of type 'TIMESTAMP WITH TIME ZONE NOT NULL'
	UpdatedAt time.Time `db:"updated_at,not_null"`
	// DeletedAt represents a database column 'deleted_at' of type 'TIMESTAMP WITH TIME ZONE NULL'
	DeletedAt *time.Time `db:"deleted_at,null"`
	// Content represents a database column 'content' of type 'TEXT NOT NULL'
	Content string `db:"content,not_null"`
}
